services:
  tetris:
    image: quay.io/str_netappontour/tetris
    build:
      context: .
    container_name: tetris
    restart: unless-stopped
    environment:
      - REACT_APP_MONEYMAKER_UPDATE_DELAY=4000
    volumes:
      - './public:/app/public'
    ports:
      - 3001:3000

  moneymaker:
    image:  quay.io/str_netappontour/moneymaker:0.1.0
    build:
      context: moneymaker/.
    container_name: moneymaker
    restart: unless-stopped
    ports:
      - 3002:3000
    volumes:
      - './moneymaker/texts:/moneymaker'

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - 3000:80
    volumes:
      - './nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
 
