apiVersion: v1
data:
  nginx.conf: |-
    server {
      listen       80;

      location /quotes {
        proxy_pass http://quotes:3002;
      }

      location /sockjs-node {
        proxy_pass http://tetris:3001;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

      location /tetris {
        proxy_pass http://tetris:3001;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
      }
    }
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: nginx
    app: tetris
  name: nginx-cm0
