kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: moneymaker-claim 
  labels:
    app: tetris
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: sc-nas-svm1